#define DEFAULT_RUN_TIME 20.0f
#define DEFAULT_CONTROLLER_IP_ADDRESS "192.168.1.56"
#define USRP_BUFFER_LENGTH 256

#define GMSK_K_VALUE 2

#define RRC_K_VALUE 2
#define RRC_M_VALUE 32
#define RRC_BETA_VALUE 0.35

#define OFDM_CP_LENGTH 6; 
#define OFDM_TAPER_LENGTH 4; 
#define OFDM_FRAME_COMPLETE_INITIAL_STATE 1

#define INTERFERER_PAYLOAD_LENGTH 40
#define INTERFERER_HEADER_LENGTH 8
