#define DEFAULT_RUN_TIME 20
#define DEFAULT_CONTROLLER_IP_ADDRESS "192.168.1.56"

#define USRP_BUFFER_LENGTH 256
#define TX_BUFFER_LENGTH   51200

#define GMSK_PAYLOAD_LENGTH 200
#define GMSK_HEADER_LENGTH 8

#define RRC_SAMPS_PER_SYM 2
#define RRC_FILTER_SEMILENGTH 32
#define RRC_BETA 0.35

#define OFDM_CP_LENGTH 16
#define OFDM_TAPER_LENGTH 8
#define OFDM_HEADER_LENGTH 64
#define OFDM_PAYLOAD_LENGTH 4196

#define DAC_RATE 64e6




